<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace RND\GremlinDSL\Traversal\Predicates\Text;

/**
 * The "containing" text-predicate.
 *
 * @see https://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates
 */
class Containing extends AbstractTextPredicate
{
    public const STEP_NAME = 'containing';
}
