<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace SpecialWeb\GremlinDSL\Traversal\Predicates\Text;

/**
 * The "notContaining" text-predicate.
 *
 * @see https://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates
 */
class NotContaining extends AbstractTextPredicate
{
    public const STEP_NAME = 'notContaining';
}
