<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace RND\GremlinDSL\Traversal\Predicates\Text;

/**
 * The "notEndingWith" text-predicate.
 *
 * @see https://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates
 */
class NotEndingWith extends AbstractTextPredicate
{
    public const STEP_NAME = 'notEndingWith';
}
