<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\Containing;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\EndingWith;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\NotContaining;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\NotEndingWith;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\NotRegex;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\NotStartingWith;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\Regex;
use SpecialWeb\GremlinDSL\Traversal\Predicates\Text\StartingWith;


if (!function_exists('containing')) {
    function containing(...$args): Containing
    {
        return new Containing(...$args);
    }
}

if (!function_exists('endingWith')) {
    function endingWith(...$args): EndingWith
    {
        return new EndingWith(...$args);
    }
}

if (!function_exists('notContaining')) {
    function notContaining(...$args): NotContaining
    {
        return new NotContaining(...$args);
    }
}

if (!function_exists('notEndingWith')) {
    function notEndingWith(...$args): NotEndingWith
    {
        return new NotEndingWith(...$args);
    }
}

if (!function_exists('notRegex')) {
    function notRegex(...$args): NotRegex
    {
        return new NotRegex(...$args);
    }
}

if (!function_exists('notStartingWith')) {
    function notStartingWith(...$args): NotStartingWith
    {
        return new NotStartingWith(...$args);
    }
}

if (!function_exists('regex')) {
    function regex(...$args): Regex
    {
        return new Regex(...$args);
    }
}

if (!function_exists('startingWith')) {
    function startingWith(...$args): StartingWith
    {
        return new StartingWith(...$args);
    }
}
