<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace RND\GremlinDSL\Traversal;

use RND\GremlinDSL\Traversal\Steps\Generated\AddEStep;
use RND\GremlinDSL\Traversal\Steps\Generated\AddVStep;
use RND\GremlinDSL\Traversal\Steps\Generated\AggregateStep;
use RND\GremlinDSL\Traversal\Steps\Generated\AndStep;
use RND\GremlinDSL\Traversal\Steps\Generated\AsStep;
use RND\GremlinDSL\Traversal\Steps\Generated\BarrierStep;
use RND\GremlinDSL\Traversal\Steps\Generated\BothEStep;
use RND\GremlinDSL\Traversal\Steps\Generated\BothStep;
use RND\GremlinDSL\Traversal\Steps\Generated\BothVStep;
use RND\GremlinDSL\Traversal\Steps\Generated\BranchStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ByStep;
use RND\GremlinDSL\Traversal\Steps\Generated\CapStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ChooseStep;
use RND\GremlinDSL\Traversal\Steps\Generated\CoalesceStep;
use RND\GremlinDSL\Traversal\Steps\Generated\CoinStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ConnectedComponentStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ConstantStep;
use RND\GremlinDSL\Traversal\Steps\Generated\CountStep;
use RND\GremlinDSL\Traversal\Steps\Generated\CyclicPathStep;
use RND\GremlinDSL\Traversal\Steps\Generated\DedupStep;
use RND\GremlinDSL\Traversal\Steps\Generated\DropStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ElementMapStep;
use RND\GremlinDSL\Traversal\Steps\Generated\EmitStep;
use RND\GremlinDSL\Traversal\Steps\Generated\FilterStep;
use RND\GremlinDSL\Traversal\Steps\Generated\FlatMapStep;
use RND\GremlinDSL\Traversal\Steps\Generated\FoldStep;
use RND\GremlinDSL\Traversal\Steps\Generated\FromStep;
use RND\GremlinDSL\Traversal\Steps\Generated\GroupCountStep;
use RND\GremlinDSL\Traversal\Steps\Generated\GroupStep;
use RND\GremlinDSL\Traversal\Steps\Generated\HasIdStep;
use RND\GremlinDSL\Traversal\Steps\Generated\HasKeyStep;
use RND\GremlinDSL\Traversal\Steps\Generated\HasLabelStep;
use RND\GremlinDSL\Traversal\Steps\Generated\HasNotStep;
use RND\GremlinDSL\Traversal\Steps\Generated\HasStep;
use RND\GremlinDSL\Traversal\Steps\Generated\HasValueStep;
use RND\GremlinDSL\Traversal\Steps\Generated\IdStep;
use RND\GremlinDSL\Traversal\Steps\Generated\IdentityStep;
use RND\GremlinDSL\Traversal\Steps\Generated\InEStep;
use RND\GremlinDSL\Traversal\Steps\Generated\InStep;
use RND\GremlinDSL\Traversal\Steps\Generated\InVStep;
use RND\GremlinDSL\Traversal\Steps\Generated\IndexStep;
use RND\GremlinDSL\Traversal\Steps\Generated\InjectStep;
use RND\GremlinDSL\Traversal\Steps\Generated\IsStep;
use RND\GremlinDSL\Traversal\Steps\Generated\KeyStep;
use RND\GremlinDSL\Traversal\Steps\Generated\LabelStep;
use RND\GremlinDSL\Traversal\Steps\Generated\LimitStep;
use RND\GremlinDSL\Traversal\Steps\Generated\LocalStep;
use RND\GremlinDSL\Traversal\Steps\Generated\LoopsStep;
use RND\GremlinDSL\Traversal\Steps\Generated\MapStep;
use RND\GremlinDSL\Traversal\Steps\Generated\MatchStep;
use RND\GremlinDSL\Traversal\Steps\Generated\MathStep;
use RND\GremlinDSL\Traversal\Steps\Generated\MaxStep;
use RND\GremlinDSL\Traversal\Steps\Generated\MeanStep;
use RND\GremlinDSL\Traversal\Steps\Generated\MinStep;
use RND\GremlinDSL\Traversal\Steps\Generated\NotStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OptionStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OptionalStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OrStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OrderStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OtherVStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OutEStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OutStep;
use RND\GremlinDSL\Traversal\Steps\Generated\OutVStep;
use RND\GremlinDSL\Traversal\Steps\Generated\PageRankStep;
use RND\GremlinDSL\Traversal\Steps\Generated\PathStep;
use RND\GremlinDSL\Traversal\Steps\Generated\PeerPressureStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ProfileStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ProgramStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ProjectStep;
use RND\GremlinDSL\Traversal\Steps\Generated\PropertiesStep;
use RND\GremlinDSL\Traversal\Steps\Generated\PropertyMapStep;
use RND\GremlinDSL\Traversal\Steps\Generated\PropertyStep;
use RND\GremlinDSL\Traversal\Steps\Generated\RangeStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ReadStep;
use RND\GremlinDSL\Traversal\Steps\Generated\RepeatStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SackStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SampleStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SelectStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ShortestPathStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SideEffectStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SimplePathStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SkipStep;
use RND\GremlinDSL\Traversal\Steps\Generated\StoreStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SubgraphStep;
use RND\GremlinDSL\Traversal\Steps\Generated\SumStep;
use RND\GremlinDSL\Traversal\Steps\Generated\TailStep;
use RND\GremlinDSL\Traversal\Steps\Generated\TimeLimitStep;
use RND\GremlinDSL\Traversal\Steps\Generated\TimesStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ToEStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ToStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ToVStep;
use RND\GremlinDSL\Traversal\Steps\Generated\TreeStep;
use RND\GremlinDSL\Traversal\Steps\Generated\UnfoldStep;
use RND\GremlinDSL\Traversal\Steps\Generated\UnionStep;
use RND\GremlinDSL\Traversal\Steps\Generated\UntilStep;
use RND\GremlinDSL\Traversal\Steps\Generated\VStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ValueMapStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ValueStep;
use RND\GremlinDSL\Traversal\Steps\Generated\ValuesStep;
use RND\GremlinDSL\Traversal\Steps\Generated\WhereStep;
use RND\GremlinDSL\Traversal\Steps\Generated\WithStep;
use RND\GremlinDSL\Traversal\Steps\Generated\WriteStep;

/**
 * @see https://tinkerpop.apache.org/docs/current/reference/
 */
class GraphTraversal extends AbstractGraphTraversal
{
    /**
     * The "V" source step.
     *
     * @param mixed $vertexIdsOrElements,...
     * @return GraphTraversal
     */
    public function V(...$vertexIdsOrElements): GraphTraversal
    {
        $step = new VStep(...$vertexIdsOrElements);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "addE" source step.
     *
     * @param mixed $args being any of:
     *                    - string edgeLabel
     *                    - mixed edgeLabelTraversal
     * @return GraphTraversal
     */
    public function addE(...$args): GraphTraversal
    {
        $step = new AddEStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "addV" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - string vertexLabel
     *                    - mixed vertexLabelTraversal
     * @return GraphTraversal
     */
    public function addV(...$args): GraphTraversal
    {
        $step = new AddVStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "aggregate" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed scope, string sideEffectKey
     *                    - string sideEffectKey
     * @return GraphTraversal
     */
    public function aggregate(...$args): GraphTraversal
    {
        $step = new AggregateStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "and" source step.
     *
     * @param mixed $andTraversals,...
     * @return GraphTraversal
     */
    public function and(...$andTraversals): GraphTraversal
    {
        $step = new AndStep(...$andTraversals);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "as" source step.
     *
     * @param string $stepLabel
     * @param mixed $stepLabels,...
     * @return GraphTraversal
     */
    public function as(string $stepLabel, ...$stepLabels): GraphTraversal
    {
        $step = new AsStep($stepLabel, ...$stepLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "barrier" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed barrierConsumer
     *                    - mixed maxBarrierSize
     * @return GraphTraversal
     */
    public function barrier(...$args): GraphTraversal
    {
        $step = new BarrierStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "both" source step.
     *
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function both(...$edgeLabels): GraphTraversal
    {
        $step = new BothStep(...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "bothE" source step.
     *
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function bothE(...$edgeLabels): GraphTraversal
    {
        $step = new BothEStep(...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "bothV" source step.
     *
     * @return GraphTraversal
     */
    public function bothV(): GraphTraversal
    {
        $step = new BothVStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "branch" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed function
     *                    - mixed branchTraversal
     * @return GraphTraversal
     */
    public function branch(...$args): GraphTraversal
    {
        $step = new BranchStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "by" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed comparator
     *                    - mixed function
     *                    - mixed function, mixed comparator
     *                    - mixed order
     *                    - string key
     *                    - string key, mixed comparator
     *                    - mixed token
     *                    - mixed traversal
     *                    - mixed traversal, mixed comparator
     * @return GraphTraversal
     */
    public function by(...$args): GraphTraversal
    {
        $step = new ByStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "cap" source step.
     *
     * @param string $sideEffectKey
     * @param mixed $sideEffectKeys,...
     * @return GraphTraversal
     */
    public function cap(string $sideEffectKey, ...$sideEffectKeys): GraphTraversal
    {
        $step = new CapStep($sideEffectKey, ...$sideEffectKeys);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "choose" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed choiceFunction
     *                    - mixed choosePredicate, mixed trueChoice
     *                    - mixed choosePredicate, mixed trueChoice, mixed falseChoice
     *                    - mixed choiceTraversal
     *                    - mixed traversalPredicate, mixed trueChoice
     *                    - mixed traversalPredicate, mixed trueChoice, mixed falseChoice
     * @return GraphTraversal
     */
    public function choose(...$args): GraphTraversal
    {
        $step = new ChooseStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "coalesce" source step.
     *
     * @param mixed $coalesceTraversals,...
     * @return GraphTraversal
     */
    public function coalesce(...$coalesceTraversals): GraphTraversal
    {
        $step = new CoalesceStep(...$coalesceTraversals);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "coin" source step.
     *
     * @param mixed $probability
     * @return GraphTraversal
     */
    public function coin($probability): GraphTraversal
    {
        $step = new CoinStep($probability);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "connectedComponent" source step.
     *
     * @return GraphTraversal
     */
    public function connectedComponent(): GraphTraversal
    {
        $step = new ConnectedComponentStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "constant" source step.
     *
     * @param mixed $e
     * @return GraphTraversal
     */
    public function constant($e): GraphTraversal
    {
        $step = new ConstantStep($e);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "count" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     * @return GraphTraversal
     */
    public function count(...$args): GraphTraversal
    {
        $step = new CountStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "cyclicPath" source step.
     *
     * @return GraphTraversal
     */
    public function cyclicPath(): GraphTraversal
    {
        $step = new CyclicPathStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "dedup" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed scope, mixed dedupLabels
     *                    - mixed dedupLabels
     * @return GraphTraversal
     */
    public function dedup(...$args): GraphTraversal
    {
        $step = new DedupStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "drop" source step.
     *
     * @return GraphTraversal
     */
    public function drop(): GraphTraversal
    {
        $step = new DropStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "elementMap" source step.
     *
     * @param mixed $propertyKeys,...
     * @return GraphTraversal
     */
    public function elementMap(...$propertyKeys): GraphTraversal
    {
        $step = new ElementMapStep(...$propertyKeys);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "emit" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed emitPredicate
     *                    - mixed emitTraversal
     * @return GraphTraversal
     */
    public function emit(...$args): GraphTraversal
    {
        $step = new EmitStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "filter" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed predicate
     *                    - mixed filterTraversal
     * @return GraphTraversal
     */
    public function filter(...$args): GraphTraversal
    {
        $step = new FilterStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "flatMap" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed function
     *                    - mixed flatMapTraversal
     * @return GraphTraversal
     */
    public function flatMap(...$args): GraphTraversal
    {
        $step = new FlatMapStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "fold" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed seed, mixed foldFunction
     * @return GraphTraversal
     */
    public function fold(...$args): GraphTraversal
    {
        $step = new FoldStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "from" source step.
     *
     * @param mixed $args being any of:
     *                    - string fromStepLabel
     *                    - mixed fromVertex
     *                    - mixed fromVertex
     * @return GraphTraversal
     */
    public function from(...$args): GraphTraversal
    {
        $step = new FromStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "group" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - string sideEffectKey
     * @return GraphTraversal
     */
    public function group(...$args): GraphTraversal
    {
        $step = new GroupStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "groupCount" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - string sideEffectKey
     * @return GraphTraversal
     */
    public function groupCount(...$args): GraphTraversal
    {
        $step = new GroupCountStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "has" source step.
     *
     * @param mixed $args being any of:
     *                    - string propertyKey
     *                    - string propertyKey, mixed value
     *                    - string propertyKey, mixed predicate
     *                    - string label, string propertyKey, mixed value
     *                    - string label, string propertyKey, mixed predicate
     *                    - string propertyKey, mixed propertyTraversal
     *                    - mixed accessor, mixed value
     *                    - mixed accessor, mixed predicate
     *                    - mixed accessor, mixed propertyTraversal
     * @return GraphTraversal
     */
    public function has(...$args): GraphTraversal
    {
        $step = new HasStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "hasId" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed id, mixed otherIds
     *                    - mixed predicate
     * @return GraphTraversal
     */
    public function hasId(...$args): GraphTraversal
    {
        $step = new HasIdStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "hasKey" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed predicate
     *                    - string label, mixed otherLabels
     * @return GraphTraversal
     */
    public function hasKey(...$args): GraphTraversal
    {
        $step = new HasKeyStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "hasLabel" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed predicate
     *                    - string label, mixed otherLabels
     * @return GraphTraversal
     */
    public function hasLabel(...$args): GraphTraversal
    {
        $step = new HasLabelStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "hasNot" source step.
     *
     * @param string $propertyKey
     * @return GraphTraversal
     */
    public function hasNot(string $propertyKey): GraphTraversal
    {
        $step = new HasNotStep($propertyKey);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "hasValue" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed value, mixed otherValues
     *                    - mixed predicate
     * @return GraphTraversal
     */
    public function hasValue(...$args): GraphTraversal
    {
        $step = new HasValueStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "id" source step.
     *
     * @return GraphTraversal
     */
    public function id(): GraphTraversal
    {
        $step = new IdStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "identity" source step.
     *
     * @return GraphTraversal
     */
    public function identity(): GraphTraversal
    {
        $step = new IdentityStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "in" source step.
     *
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function in(...$edgeLabels): GraphTraversal
    {
        $step = new InStep(...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "inE" source step.
     *
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function inE(...$edgeLabels): GraphTraversal
    {
        $step = new InEStep(...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "inV" source step.
     *
     * @return GraphTraversal
     */
    public function inV(): GraphTraversal
    {
        $step = new InVStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "index" source step.
     *
     * @return GraphTraversal
     */
    public function index(): GraphTraversal
    {
        $step = new IndexStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "inject" source step.
     *
     * @param mixed $injections,...
     * @return GraphTraversal
     */
    public function inject(...$injections): GraphTraversal
    {
        $step = new InjectStep(...$injections);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "is" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed value
     *                    - mixed predicate
     * @return GraphTraversal
     */
    public function is(...$args): GraphTraversal
    {
        $step = new IsStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "key" source step.
     *
     * @return GraphTraversal
     */
    public function key(): GraphTraversal
    {
        $step = new KeyStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "label" source step.
     *
     * @return GraphTraversal
     */
    public function label(): GraphTraversal
    {
        $step = new LabelStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "limit" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed scope, mixed limit
     *                    - mixed limit
     * @return GraphTraversal
     */
    public function limit(...$args): GraphTraversal
    {
        $step = new LimitStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "local" source step.
     *
     * @param mixed $localTraversal
     * @return GraphTraversal
     */
    public function local($localTraversal): GraphTraversal
    {
        $step = new LocalStep($localTraversal);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "loops" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - string loopName
     * @return GraphTraversal
     */
    public function loops(...$args): GraphTraversal
    {
        $step = new LoopsStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "map" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed function
     *                    - mixed mapTraversal
     * @return GraphTraversal
     */
    public function map(...$args): GraphTraversal
    {
        $step = new MapStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "match" source step.
     *
     * @param mixed $matchTraversals,...
     * @return GraphTraversal
     */
    public function match(...$matchTraversals): GraphTraversal
    {
        $step = new MatchStep(...$matchTraversals);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "math" source step.
     *
     * @param string $expression
     * @return GraphTraversal
     */
    public function math(string $expression): GraphTraversal
    {
        $step = new MathStep($expression);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "max" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     * @return GraphTraversal
     */
    public function max(...$args): GraphTraversal
    {
        $step = new MaxStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "mean" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     * @return GraphTraversal
     */
    public function mean(...$args): GraphTraversal
    {
        $step = new MeanStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "min" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     * @return GraphTraversal
     */
    public function min(...$args): GraphTraversal
    {
        $step = new MinStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "not" source step.
     *
     * @param mixed $notTraversal
     * @return GraphTraversal
     */
    public function not($notTraversal): GraphTraversal
    {
        $step = new NotStep($notTraversal);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "option" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed pickToken, mixed traversalOption
     *                    - mixed traversalOption
     * @return GraphTraversal
     */
    public function option(...$args): GraphTraversal
    {
        $step = new OptionStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "optional" source step.
     *
     * @param mixed $optionalTraversal
     * @return GraphTraversal
     */
    public function optional($optionalTraversal): GraphTraversal
    {
        $step = new OptionalStep($optionalTraversal);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "or" source step.
     *
     * @param mixed $orTraversals,...
     * @return GraphTraversal
     */
    public function or(...$orTraversals): GraphTraversal
    {
        $step = new OrStep(...$orTraversals);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "order" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     * @return GraphTraversal
     */
    public function order(...$args): GraphTraversal
    {
        $step = new OrderStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "otherV" source step.
     *
     * @return GraphTraversal
     */
    public function otherV(): GraphTraversal
    {
        $step = new OtherVStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "out" source step.
     *
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function out(...$edgeLabels): GraphTraversal
    {
        $step = new OutStep(...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "outE" source step.
     *
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function outE(...$edgeLabels): GraphTraversal
    {
        $step = new OutEStep(...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "outV" source step.
     *
     * @return GraphTraversal
     */
    public function outV(): GraphTraversal
    {
        $step = new OutVStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "pageRank" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed alpha
     * @return GraphTraversal
     */
    public function pageRank(...$args): GraphTraversal
    {
        $step = new PageRankStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "path" source step.
     *
     * @return GraphTraversal
     */
    public function path(): GraphTraversal
    {
        $step = new PathStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "peerPressure" source step.
     *
     * @return GraphTraversal
     */
    public function peerPressure(): GraphTraversal
    {
        $step = new PeerPressureStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "profile" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - string sideEffectKey
     * @return GraphTraversal
     */
    public function profile(...$args): GraphTraversal
    {
        $step = new ProfileStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "program" source step.
     *
     * @param mixed $vertexProgram
     * @return GraphTraversal
     */
    public function program($vertexProgram): GraphTraversal
    {
        $step = new ProgramStep($vertexProgram);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "project" source step.
     *
     * @param string $projectKey
     * @param mixed $otherProjectKeys,...
     * @return GraphTraversal
     */
    public function project(string $projectKey, ...$otherProjectKeys): GraphTraversal
    {
        $step = new ProjectStep($projectKey, ...$otherProjectKeys);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "properties" source step.
     *
     * @param mixed $propertyKeys,...
     * @return GraphTraversal
     */
    public function properties(...$propertyKeys): GraphTraversal
    {
        $step = new PropertiesStep(...$propertyKeys);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "property" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed cardinality, mixed key, mixed value, mixed keyValues
     *                    - mixed key, mixed value, mixed keyValues
     * @return GraphTraversal
     */
    public function property(...$args): GraphTraversal
    {
        $step = new PropertyStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "propertyMap" source step.
     *
     * @param mixed $propertyKeys,...
     * @return GraphTraversal
     */
    public function propertyMap(...$propertyKeys): GraphTraversal
    {
        $step = new PropertyMapStep(...$propertyKeys);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "range" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed scope, mixed low, mixed high
     *                    - mixed low, mixed high
     * @return GraphTraversal
     */
    public function range(...$args): GraphTraversal
    {
        $step = new RangeStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "read" source step.
     *
     * @return GraphTraversal
     */
    public function read(): GraphTraversal
    {
        $step = new ReadStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "repeat" source step.
     *
     * @param mixed $args being any of:
     *                    - string loopName, mixed repeatTraversal
     *                    - mixed repeatTraversal
     * @return GraphTraversal
     */
    public function repeat(...$args): GraphTraversal
    {
        $step = new RepeatStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "sack" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed sackOperator
     * @return GraphTraversal
     */
    public function sack(...$args): GraphTraversal
    {
        $step = new SackStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "sample" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed scope, mixed amountToSample
     *                    - mixed amountToSample
     * @return GraphTraversal
     */
    public function sample(...$args): GraphTraversal
    {
        $step = new SampleStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "select" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed column
     *                    - mixed pop, string selectKey
     *                    - mixed pop, string selectKey1, string selectKey2, mixed otherSelectKeys
     *                    - mixed pop, mixed keyTraversal
     *                    - string selectKey
     *                    - string selectKey1, string selectKey2, mixed otherSelectKeys
     *                    - mixed keyTraversal
     * @return GraphTraversal
     */
    public function select(...$args): GraphTraversal
    {
        $step = new SelectStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "shortestPath" source step.
     *
     * @return GraphTraversal
     */
    public function shortestPath(): GraphTraversal
    {
        $step = new ShortestPathStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "sideEffect" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed consumer
     *                    - mixed sideEffectTraversal
     * @return GraphTraversal
     */
    public function sideEffect(...$args): GraphTraversal
    {
        $step = new SideEffectStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "simplePath" source step.
     *
     * @return GraphTraversal
     */
    public function simplePath(): GraphTraversal
    {
        $step = new SimplePathStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "skip" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed scope, mixed skip
     *                    - mixed skip
     * @return GraphTraversal
     */
    public function skip(...$args): GraphTraversal
    {
        $step = new SkipStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "store" source step.
     *
     * @param string $sideEffectKey
     * @return GraphTraversal
     */
    public function store(string $sideEffectKey): GraphTraversal
    {
        $step = new StoreStep($sideEffectKey);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "subgraph" source step.
     *
     * @param string $sideEffectKey
     * @return GraphTraversal
     */
    public function subgraph(string $sideEffectKey): GraphTraversal
    {
        $step = new SubgraphStep($sideEffectKey);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "sum" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     * @return GraphTraversal
     */
    public function sum(...$args): GraphTraversal
    {
        $step = new SumStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "tail" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - mixed scope
     *                    - mixed scope, mixed limit
     *                    - mixed limit
     * @return GraphTraversal
     */
    public function tail(...$args): GraphTraversal
    {
        $step = new TailStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "timeLimit" source step.
     *
     * @param mixed $timeLimit
     * @return GraphTraversal
     */
    public function timeLimit($timeLimit): GraphTraversal
    {
        $step = new TimeLimitStep($timeLimit);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "times" source step.
     *
     * @param mixed $maxLoops
     * @return GraphTraversal
     */
    public function times($maxLoops): GraphTraversal
    {
        $step = new TimesStep($maxLoops);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "to" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed direction, mixed edgeLabels
     *                    - string toStepLabel
     *                    - mixed toVertex
     *                    - mixed toVertex
     * @return GraphTraversal
     */
    public function to(...$args): GraphTraversal
    {
        $step = new ToStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "toE" source step.
     *
     * @param mixed $direction
     * @param mixed $edgeLabels,...
     * @return GraphTraversal
     */
    public function toE($direction, ...$edgeLabels): GraphTraversal
    {
        $step = new ToEStep($direction, ...$edgeLabels);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "toV" source step.
     *
     * @param mixed $direction
     * @return GraphTraversal
     */
    public function toV($direction): GraphTraversal
    {
        $step = new ToVStep($direction);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "tree" source step.
     *
     * @param mixed $args being any of:
     *                    - empty
     *                    - string sideEffectKey
     * @return GraphTraversal
     */
    public function tree(...$args): GraphTraversal
    {
        $step = new TreeStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "unfold" source step.
     *
     * @return GraphTraversal
     */
    public function unfold(): GraphTraversal
    {
        $step = new UnfoldStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "union" source step.
     *
     * @param mixed $unionTraversals,...
     * @return GraphTraversal
     */
    public function union(...$unionTraversals): GraphTraversal
    {
        $step = new UnionStep(...$unionTraversals);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "until" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed untilPredicate
     *                    - mixed untilTraversal
     * @return GraphTraversal
     */
    public function until(...$args): GraphTraversal
    {
        $step = new UntilStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "value" source step.
     *
     * @return GraphTraversal
     */
    public function value(): GraphTraversal
    {
        $step = new ValueStep();
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "valueMap" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed propertyKeys
     *                    - mixed includeTokens, mixed propertyKeys
     * @return GraphTraversal
     */
    public function valueMap(...$args): GraphTraversal
    {
        $step = new ValueMapStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "values" source step.
     *
     * @param mixed $propertyKeys,...
     * @return GraphTraversal
     */
    public function values(...$propertyKeys): GraphTraversal
    {
        $step = new ValuesStep(...$propertyKeys);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "where" source step.
     *
     * @param mixed $args being any of:
     *                    - mixed predicate
     *                    - string startKey, mixed predicate
     *                    - mixed whereTraversal
     * @return GraphTraversal
     */
    public function where(...$args): GraphTraversal
    {
        $step = new WhereStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "with" source step.
     *
     * @param mixed $args being any of:
     *                    - string key
     *                    - string key, mixed value
     * @return GraphTraversal
     */
    public function with(...$args): GraphTraversal
    {
        $step = new WithStep(...$args);
        $this->steps->add($step);

        return new static();
    }

    /**
     * The "write" source step.
     *
     * @return GraphTraversal
     */
    public function write(): GraphTraversal
    {
        $step = new WriteStep();
        $this->steps->add($step);

        return new static();
    }
}
