<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace RND\GremlinDSL\Traversal\Steps\Source;

class WithSourceStep extends \RND\GremlinDSL\Traversal\Steps\AbstractStep
{
}
