<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace SpecialWeb\GremlinDSL\Traversal\Predicates;

/**
 * The "inside" predicate.
 *
 * @see https://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates
 */
class Inside extends AbstractPredicate
{
    public const STEP_NAME = 'inside';
}
