<?php

/**
 * This is an autogenerated file. Changes will be lost on next generation.
 */

declare(strict_types=1);

namespace RND\GremlinDSL\Traversal\Predicates;

/**
 * The "outside" predicate.
 *
 * @see https://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates
 */
class Outside extends AbstractPredicate
{
    public const STEP_NAME = 'outside';
}
